# Generated by Django 4.1.4 on 2023-01-15 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emoji_picker.widgets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('images', models.ImageField(upload_to='Upload Media Root')),
                ('Bio', models.CharField(max_length=150, verbose_name=emoji_picker.widgets.EmojiPickerTextareaAdmin)),
            ],
        ),
    ]
