# Generated by Django 4.1.4 on 2023-02-04 11:15

import Invite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invite', '0002_alter_user_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='first_name',
            field=models.CharField(default=Invite.models.mydate, max_length=30),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_name',
            field=models.CharField(default=Invite.models.mydate, max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Bio',
            field=models.CharField(max_length=300),
        ),
    ]
