# Generated by Django 4.1.4 on 2023-02-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invite', '0003_user_profile_first_name_user_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='images',
            field=models.ImageField(blank=True, default='photos/images.png', null=True, upload_to='Upload Media Root'),
        ),
    ]
