# Generated by Django 4.1.4 on 2023-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invite', '0004_alter_user_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='Upload Media Root'),
        ),
    ]
