# Generated by Django 4.1.4 on 2023-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invite', '0006_alter_user_profile_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
